pipeline {
  agent none
  options {
    disableConcurrentBuilds()
    buildDiscarder(logRotator(numToKeepStr: '8', daysToKeepStr: '20'))
  }
  stages {
    stage('GPU Testing') {
      parallel {
        stage('MatrixAlgebraKitCUDAExt julia-lts') {
	        options {
            timeout(time: 45, unit: 'MINUTES')
          }
          agent {
            dockerfile {
              label 'gpu&&v100'
              filename 'Dockerfile'
              dir 'jenkins'
              additionalBuildArgs  '--build-arg JULIA=1.10'
              args '--gpus "device=1"'
            }
          }
          environment {
            HOME = pwd(tmp:true)
            OMP_NUM_THREADS = 4
            JULIA_NUM_THREADS = 4
          }
          steps {
            sh '''
              julia --project=. -e 'using Pkg: Pkg; Pkg.test("MatrixAlgebraKit"; test_args=["--group=cuda"])'
            '''
          }
        }
        stage('MatrixAlgebraKitCUDAExt julia-1') {
	        options {
            timeout(time: 45, unit: 'MINUTES')
          }
          agent {
            dockerfile {
              label 'gpu&&v100'
              filename 'Dockerfile'
              dir 'jenkins'
              additionalBuildArgs  '--build-arg JULIA=1.11'
              args '--gpus "device=1"'
            }
          }
          environment {
            HOME = pwd(tmp:true)
            OMP_NUM_THREADS = 4
            JULIA_NUM_THREADS = 4
          }
          steps {
            sh '''
              julia --project=. -e 'using Pkg: Pkg; Pkg.test("MatrixAlgebraKit"; test_args=["--group=cuda"])'
            '''
          }
        }
      }
    }
  }
}
