name: FormatCheck

permissions:
  contents: read
  checks: write
  issues: write
  pull-requests: write

on:
  push:
    branches:
      - 'main'
      - 'master'
    tags: '*'
  pull_request:
    branches:
      - 'main'
      - 'master'

jobs:
  formatcheck:
    name: "Format Check"
    uses: "QuantumKitHub/QuantumKitHubActions/.github/workflows/FormatCheck.yml@main"
